# https://peps.python.org/pep-0621/#example
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata

[project]
name = "benimang"
version = "0.5.26"
description = "Utils library for Beni"
requires-python = ">=3.10"
keywords = ["benimang", "beni"]
authors = [{ name = 'Beni Mang', email = 'benimang@126.com' }]
maintainers = [{ name = 'Beni Mang', email = 'benimang@126.com' }]

dependencies = [
  'aioconsole',
  'aiofiles',
  'aiohttp',
  'aiomysql',
  'async_timeout',
  'build',
  'chardet',
  'colorama',
  'cryptography',
  'nest-asyncio',
  'orjson',
  # 'playwright',
  'pretty_errors',
  'prettytable',
  'pydantic',
  'pyjwt',
  'pyperclip',
  'pytest',
  'pytest-asyncio',
  'pyyaml',
  'qiniu',
  'rich',
  'tqdm',
  'twine',
  'typer',
  'tzdata',
]
