[tool.poetry]
name = "datable-ai"
version = "0.0.1"
description = "datable-ai"
authors = ["datable <dev@datable.jp>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.23.1"
langchain-openai = "^0.1.3"
python-dotenv = "^1.0.1"
langchain-anthropic = "^0.1.11"
pytest = "^8.1.1"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
black = "^24.4.0"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
