[tool.poetry]
name = "hermesbaby"
version = "0.1.4"
description = "The Software Engineers' Typewriter"
authors = ["Alexander Mann-Wahrenberg (basejumpa) <alexander.mannwahrenberg@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sphinx = "^7.3.7"

[tool.poetry.scripts]
hermesbaby = "hermesbaby.cli:main"
hb = "hermesbaby.cli:main"

[build-system]
requires = [
    "poetry-core",
    "setuptools>=46.1.0", 
    "setuptools_scm[toml]>=5"
]

# build-backend = "poetry.core.masonry.api"
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# For smarter version schemes and other configuration options,
# check out https://github.com/pypa/setuptools_scm
version_scheme = "no-guess-dev"