[tool.poetry]
name = "langreact"
version = "0.1.0"
description = "LangReact Project"
authors = ["zhangli <max_and_min@163.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "core", format = "wheel" },
    { include = "core", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.16"
openai = "^1.23.2"
milvus = "^2.3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
