[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "linalgebralib"
version = "0.0.31"
authors = [
  { name="Adam Authur", email="aauthur@tamu.edu" },
]
description = "This package contains a library of methods and classes relating to Linear Algebra."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/aauthur/LinAlgebraLib"