[project]
name = "competex"
version = "1.1"
authors = [
  { name="Sike Brothers", email="sikebros@gmail.com" },
]
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]