[tool.poetry]
name = "linuxsysstat"
version = "0.1.2"
description = "Linux System stat"
authors = ["Bharath <learnit.linux@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
psutil = "^5.9.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
linuxsysstat = 'linuxsysstat:main'

