[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tf-ctc"
version = "0.1.5"
authors = [
    { name="Marcel Claramunt", email="marcel@moveread.com" }
]
description = "CTC with tensorflow, simplified"
dependencies = [
    "jaxtyping", "tf-tools", "tensorflow"
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.optional-dependencies]
test = [
    "pytest", "hypothesis"
]

# [project.urls]
# repo = "<GIT_REPO_URL>"
