[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=69.5.1"]

[tool.setuptools]
package-dir = {"" = "src"}

[project]
authors = [{name = "Alim Abrekov", email = "alimabrekov@outlook.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
description = "Pythonic-cache library for caching, which has everything you need out of the box and nothing extra."
name = "pythonic-cache"
readme = "README.md"
requires-python = ">=3.11.0"
version = "0.4.0"

[project.optional-dependencies]
fastapi = [
  "fastapi>=0.110.2",
]
flask = [
  "flask>=3.0.3",
]
lint = [
  "black>=24.3.0",
  "isort>=5.13.2",
  "mypy>=1.9.0",
  "flake8>=7.0.0",
  "flake8-pyproject>=1.2.3",
]
testing = [
  "pytest>=8.1.1",
  "pytest-asyncio>=0.23.6",
  "httpx>=0.27.0",
]

[tool.pytest.init_options]
filterwarnings = [
  "ignore::DeprecationWarning",
]
pythonpath = [
  "src",
]
testpaths = [
  "tests",
]

[tool.black]
line-length = 88
target-version = [
  "py311",
]

[tool.isort]
profile = "black"

[tool.mypy]
exclude = "tests/"
python_version = "3.11"

[tool.flake8]
max-line-length = 88

[project.urls]
"Bug Tracker" = "https://github.com/Dark04072006/pythonic-cache/issues"
"Homepage" = "https://github.com/Dark04072006/pythonic-cache"
