[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-data = {"sample" = ["*.dat"]}


[project]
name = 'gravithon'
keywords = ['physics', '2d', '3d', 'engine'] #TODO
version = '0.0.5'
description = 'Create multy-dimensional python spaces' #TODO
readme = 'README.md'

dependencies = [
    'numpy',
    'multipledispatch',
    'tkinter'
]

authors = [
  { name='Yehuda Elyasaf', email='30yehuda26@gmail.com' },
]
maintainers = [
  { name='Yehuda Elyasaf', email='30yehuda26@gmail.com' },
]

license = {file = 'LICESNSE'}

classifiers = [
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]

[project.urls]
Homepage = 'https://github.com/YehudaElyasaf/gravithon'
Issues = 'https://github.com/YehudaElyasaf/gravithon/issues' #TODO
