[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools-scm",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "flexible_semantic_kernel" # 项目名
version = "1.0.1.dev0" # 版本号
authors = [
  { name="YitongCao", email="ytea.cao@gmail.com" },
]
description = "flexible-semantic-kernel" # 说明
readme = "README.md" # pypi介绍内容会读取的readme文件
requires-python = ">=3.10" # 依赖
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "aiohttp >= 3.8",
    "numpy >= 1.24.2",
    "openai >= 1.0",
    "aiofiles >= 23.1.0",
    "python-dotenv == 1.0.0",
    "regex >= 2023.6.3",
    "openapi_core >= 0.18.0",
    "prance >= 23.6.21.0",
    "pydantic > 2",
    "motor >= 3.3.1",
    "pre-commit == 3.5.0",
    "black >= 23.12.0",
    "ruff == 0.2.2",
    "ipykernel >=6.21.1",
    "pytest == 7.4.3",
    "pytest-asyncio == 0.23.2",
    "snoop == 0.4.3",
    "pytest-cov == 4.1.0",
    "google-generativeai >=0.1,<0.3",
    "grpcio-status >=1.53.0",
    "transformers >= 4.28.1",
    "sentence-transformers >= 2.2.2",
    "torch == 2.0.0",
    "qdrant-client >=1.3.2",
    "chromadb == 0.4.13",
    "pymilvus == 2.3.5",
    "milvus == 2.3.5",
    "weaviate-client >= 3.18.0",
    "pinecone-client >= 2.2.2",
    "psycopg-pool >= 3.1.7",
    "psycopg >=3.1.9",
    "psycopg-binary >=3.1.9",
    "redis >= 4.6.0",
    "usearch == 1.1.1",
    "pyarrow >= 12.0.1,<15.0.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flexible_semantic_kernel*"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.json"]