[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kv-api"
version = "0.1.7"
authors = [
  {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "API spec for an async Key-Value DB"
dependencies = [
  "haskellian"
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.urls]
repo = "https://github.com/moveread/python-kv"
home = "https://github.com/moveread/python-kv/tree/main/kv-api"

# [project.optional-dependencies]
# test = [
#   "pytest < 5.0.0",
#   "pytest-cov[all]"
# ]