[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "unit_simple"
version = "1.0.14"
authors = [
  { name="Samuel AndrÃ©s", email="samuel.andres@yahoo.fr" },
]
description = "A simple measurement unit API to handle basic unit conversions."
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["units", "converter", "unit converter", "measure", "units of measurement"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[project.urls]
"Homepage" = "https://github.com/SamuelAndresPascal/cosmoloj-py"