[tool.poetry]
name = "bookcache"
version = "0.0.4"
description = "An in-memory keystore caching system."
authors = ["NotAussie <NotAussie@duck.com>"]
readme = "README.md"
license = "MIT"
keywords = ["caching", "cache", "keystore"]
repository = "https://github.com/NotAussie/bookcache"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Topic :: Database",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
