[tool.poetry]
name = "bife"
version = "0.1.11"
description = ""
authors = ["Adrien <adrienv.sui@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pick = "^2.2.0"
jinja2 = "^3.1.3"
mako = "^1.3.3"


[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.2"
blue = "^0.9.1"
isort = "^5.13.2"
pytest-cov = "^5.0.0"
pytest = "^8.1.1"
sqlalchemy = "^2.0.29"
fastapi = "^0.110.2"
pyjwt = "^2.8.0"
argon2-cffi = "^23.1.0"
python-dotenv = "^1.0.1"
uvicorn = "^0.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "blue . && isort ."
pre_test = "task lint"
test = "pytest -s -x --cov=advice_doc -vv"

[tool.djlint]
profile="jinja"

[tool.poetry.scripts]
bife = "bife.cli:cli"