[tool.poetry]
name = "oldschool_management_tools"
version = "0.1.11"
description = ""
authors = ["Alasdair McBride <alasdair.mcbride@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pywin32 = {version="^306", platform="win32"}
termcolor = "^2.2.0"
colorama = "^0.4.6"
pyyaml = "^6.0"
dataclasses-json = "^0.5.14"
pandas = "^2.2.2"
fastparquet = "^2023.7.0"
pyarrow = "^16.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
mypy = "^1.9.0"
types-pywin32 = "^306.0.0.20240408"
pandas-stubs = "^2.2.1.240316"
types-pyyaml = "^6.0.12.20240311"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tools = "oldschool_management_tools.mgmt_tools_cmd:run"
