[tool.poetry]
name = "nestipy-decorator"
version = "0.1.3"
description = ""
authors = ["tsiresymila <tsiresymila@gmail.com>"]
readme = "README.md"
packages = [{include = "nestipy_decorator", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
nestipy-metadata = "^0.1.0"
nestipy-ioc = "^0.1.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
